### ISSUE TITLE
cut a new release?

### ISSUE THREAD

**Issue by hexfusion** [Tuetuopay/protoc-gen-tonic#2]
It would be useful to have a version tag of the initial code for tracking purposes and also to reference the buf registry version.

**Comment by Tuetuopay** [comment]
I should put a warning in the repo. This is _not_ the published crate on crates.io nor in buf registry. What you're looking for is https://github.com/neoeinstein/protoc-gen-prost which is the upstream for those public versions. They do have proper tags :)
