### ISSUE TITLE
invalid parameter: no_build_server

### ISSUE THREAD

**Issue by henrikrudstrom** [Tuetuopay/protoc-gen-tonic#4]
Hi, 
Im having trouble passing options to `protoc-gen-tonic`:
```
❯ protoc  --tonic_out=rpc --tonic_opt=no_build_server test.proto
--tonic_out: invalid parameter: no_build_server
```

Im also having the same trouble with `protoc-gen-prost`: https://github.com/Tuetuopay/protoc-gen-prost/issues/3

(im on a macbook with apple silicon processor, and using `zsh`)

**Comment by Tuetuopay** [comment]
Hi, sorry for the late response.

How did you install the plugin? If through crates.io, they you're likely not using this one but the one over at https://github.com/neoeinstein/protoc-gen-prost. His is the one published on crates.io, while mine was developed in parallel and did not end up being released anywhere.
